version: '2'

services:
    kafka-base:
        image: spotify/kafka
        ports:
          - "2181:2181"
          - "9092:9092"
        environment:
          ADVERTISED_HOST: kafka
          ADVERTISED_PORT: 9092
        restart: always
