version: '2'

services:
    kafka-base:
        image: spotify/kafka
        ports:
          - "2181:2181"
          - "9092:9092"
        environment:
          ADVERTISED_HOST: kafka
          ADVERTISED_PORT: 9092
        restart: always

    grafana-base:
        image: kamon/grafana_graphite
        ports:
          - "80:80"
          - "81:81"
          - "8125:8125/udp"
          - "8126:8126"