version: '2'

services:
    ########### CORE #################

    #TODO add 3 kafka node cluster
    kafka:
        extends:
            file: base-containers.yml
            service: kafka-base

    #TODO rename statsd -> grafana
    statsd:
        extends:
            file: base-containers.yml
            service: grafana-base
        volumes:
            - ./compose-resources/grafana/conf:/opt/grafana/conf/
            - ./compose-resources/grafana/dashboards:/src/dashboards/

    # initializes grafana and dies.
    statsd-init:
        image: kamon/grafana_graphite
        volumes:
            - ./compose-resources/grafana/init:/init/scripts/
        command: bash /init/scripts/grafana-init.sh
        links:
            - statsd:statsd
        depends_on:
            - statsd

    ########### COMPONENTS ###########

    krampus-source:
        image: codejitsu/krampus-source:0.1-SNAPSHOT
        depends_on:
            - kafka
        volumes:
            - /tmp/share:/tmp/share
        stdin_open: true
        restart: always

    krampus-producer:
        image: codejitsu/krampus-producer:0.1-SNAPSHOT
        depends_on:
            - kafka
            - krampus-source
        volumes:
            - /tmp/share:/tmp/share
        stdin_open: true
        links:
            - kafka:kafka
        restart: always

    krampus-metrics-aggregator:
        image: codejitsu/krampus-metrics-aggregator:0.1-SNAPSHOT
        depends_on:
            - kafka
            - statsd
        links:
            - kafka:kafka
        restart: always
