version: '2'

services:
    ########### CORE #################

    kafka:
        extends:
            file: base-containers.yml
            service: kafka-base

    ########### COMPONENTS ###########

    krampus-source:
        image: codejitsu/krampus-source:0.1-SNAPSHOT
        depends_on:
            - kafka
        volumes:
            - /tmp/share:/tmp/share
        stdin_open: true
        restart: always

    krampus-producer:
        image: codejitsu/krampus-producer:0.1-SNAPSHOT
        depends_on:
            - kafka
            - krampus-source
        volumes:
            - /tmp/share:/tmp/share
        stdin_open: true
        links:
            - kafka:kafka
        restart: always
